spring.application.name=GazApp

server.port = 8082

app.dir = uploads
spring.servlet.multipart.enabled = true
spring.servlet.max-file-size = 1000000000


spring.datasource.url = jdbc:postgresql://localhost:5432/gazapp
spring.datasource.username = postgres
spring.datasource.password = galand


spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


logging.level.root = INFO
logging.level.learn.spring_boot.crud = DEBUG
logging.level.hibernate.SQL = DEBUG
logging.pattern.console = %d{yyyy-MM-dd HH:mm:ss} - %msg%n